#!/bin/bash
#
# pre-commit-excel: have git handle xlsx files by deflating them and storing
#                   the XML in the repository, not the zip file. 
#
#                   companion to post-commit-excel
#

# -- config -- #
TMP_PREFIX='.~' # prefix XML directory--should NOT conflict with 
                   # anything in your repo

# -- end config -- #

echo
echo "=== Pre-commit XLSX processing ===="

unpack_xlsx () {
    # unzip the xlsx file 
    if [ -e "$1" ]; then
        if [ -e "${TMP_PREFIX}$1" ]; then rm -rf "${TMP_PREFIX}$1"; fi
        unzip "$1" -d "${TMP_PREFIX}$1"
    else
        # abort the commit if this isn't an excel file somehow
#        # !!!THIS ISN'T DOING ANYTHING YET!!!                      /!\
        return 1
    fi
}

# make it easy to iterate over subdirectories
shopt -s globstar

# check that the swap file isn't there
for i in **/*.xlsx; do 
    dir=$(dirname "$i")
    file=$(basename "$i")
    if [ -e "$dir/~\$$file" ]; then
        echo "$file swap file present: close xlsx file before committing"
        exit 2 # excel file is open
    fi
done

# unpack all the zipfiles
for i in **/*.xlsx; do 
    dir=$(dirname "$i")
    file=$(basename "$i")
    cd "$dir"
    unpack_xlsx "$file"
    cd -
    # unstage the actual excel file
    git reset HEAD "$dir/$file"
    git add "$dir/${TMP_PREFIX}$file"
done

echo "=== End of pre-commit processing ==="
echo

